# Generated by Django 3.0.5 on 2020-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('symbol', models.CharField(default=None, max_length=12, primary_key=True, serialize=False)),
                ('test', models.CharField(blank=True, default='111', max_length=12, null=True)),
            ],
        ),
    ]
