# Generated by Django 3.0.5 on 2020-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='test',
            field=models.TextField(blank=True, default='111', null=True),
        ),
    ]
