# Generated by Django 3.0.5 on 2020-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockbuddy', '0002_auto_20200612_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
