# Generated by Django 3.0.5 on 2020-06-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockbuddy', '0003_auto_20200612_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='test',
            new_name='prediction3',
        ),
    ]
