# Generated by Django 3.0.5 on 2020-06-12 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockbuddy', '0011_auto_20200612_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='mlprediction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True), null=True, size=None),
        ),
    ]
