# Generated by Django 3.0.5 on 2020-06-14 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockbuddy', '0013_auto_20200612_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='listreport',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
